# Generated by Django 3.2.7 on 2022-01-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('marks', models.JSONField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('input_format', models.TextField(blank=True, null=True)),
                ('output_format', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('sample_input', models.JSONField(blank=True, null=True)),
                ('sample_output', models.JSONField(blank=True, null=True)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('test_case_input', models.JSONField(blank=True, null=True)),
                ('test_case_output', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
