# Generated by Django 3.2.7 on 2022-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_results_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('test_start', models.DateTimeField(blank=True, null=True)),
                ('test_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
