# Generated by Django 3.2.7 on 2022-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_para_paraopt_paraqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='avg_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
