# Generated by Django 3.2.7 on 2022-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subject_avg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
