# Generated by Django 4.0 on 2022-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220201_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='apt',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='aw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='cf',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='dom',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
