# Generated by Django 4.0 on 2022-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_test_apt_test_aw_test_cf_test_dom'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='c',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='p',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
