# Generated by Django 4.0 on 2022-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_test_c_test_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
