# Generated by Django 4.0 on 2022-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_questions_title2_alter_questions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='title2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
