# Generated by Django 3.2.7 on 2022-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_options_title2_alter_options_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='imgId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
