# Generated by Django 3.2.7 on 2022-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='percent_10_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='percent_12_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
