# Generated by Django 3.2.7 on 2022-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220208_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_qs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
