# Generated by Django 3.2.7 on 2022-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_myuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avgCGPA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='branch',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='college',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='internships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='year',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
