# Generated by Django 4.0 on 2022-02-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_feedback_takefeeback'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
