# Generated by Django 4.0 on 2022-02-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_test_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='takeFeeback',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='token',
        ),
        migrations.AddField(
            model_name='myuser',
            name='takeFeeback',
            field=models.IntegerField(default=1),
        ),
    ]
