# Generated by Django 4.0 on 2022-02-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_feedback_takefeeback_remove_myuser_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='takeFeeback',
            new_name='takeFeedback',
        ),
    ]
