# Generated by Django 3.2.7 on 2022-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_takefeeback_myuser_takefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='change_pass_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
