# Generated by Django 4.0 on 2022-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_myuser_change_pass_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleges', models.JSONField(blank=True, null=True)),
                ('departments', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
