# Generated by Django 3.2.7 on 2022-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_questionjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
