# Generated by Django 4.0.4 on 2022-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_test_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='percent_10_std',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='percent_12_std',
            field=models.FloatField(default=1),
        ),
    ]
