# Generated by Django 4.0 on 2022-05-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
