export const quesData = {
  data: {
    Aptitude: {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 0,
      avg: 0,
      time: "00:00:20",
    },
    "Computer Fundamentals": {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 0,
      avg: 0,
      time: "00:00:20",
    },
    Domain: {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 0,
      avg: 0,
      time: "00:00:20",
    },
    Personality: {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 0,
      avg: 0,
      time: "00:00:20",
    },
    "Verbal Reasoning": {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 3,
      avg: 30,
      time: "00:00:20",
    },
    Coding: {
      easy: [],
      medium: [],
      hard: [],
      qs: 0,
      maxQs: 3,
      avg: 30,
      time: "00:00:20",
    },
  },
};
